{
  'collectionLink': 'https://www.dropbox.com/scl/fi/rnk1m8cdfzpdd9q8patgw/user.v2.dlens?rlkey=6s1y39mnhpszh0j2qqhizkeae&st=wsaonjun&dl=0',
  'moxfield': {
    'username': 'kvl',
    'password': 'Cyborg10',
  }
}
