{
  'collectionLink': 'https://www.dl.dropboxusercontent.com/scl/fi/rnk1m8cdfzpdd9q8patgw/user.v2.dlens?rlkey=6s1y39mnhpszh0j2qqhizkeae&dl=0',
  'moxfield': {
    'username': 'KVL',
    'password': 'Cyborg10',
  }
}
